<?xml version="1.0" encoding="utf-8"?>
<definitions 
    xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" 
    xmlns:wsp="http://www.w3.org/ns/ws-policy" 
    xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" 
    xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" 
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
    xmlns:tns="http://timedtester.org/" 
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
    xmlns="http://schemas.xmlsoap.org/wsdl/" 
    targetNamespace="http://timedtester.org/" 
    name="TimedTesterWS">
    <types>
        <xsd:schema>
            <xsd:import namespace="http://timedtester.org/" 
                        schemaLocation="data.xsd"/>
        </xsd:schema>
    </types>
    <message name="add">
        <part name="parameters" element="tns:add"/>
    </message>
    <message name="addResponse">
        <part name="parameters" element="tns:addResponse"/>
    </message>
    
    <message name="addAsync">
        <part name="parameters" element="tns:addAsync"/>
    </message>
    <message name="addAsyncResponse">
        <part name="parameters" element="tns:addAsyncResponse"/>
    </message>
    
    <portType name="TimedTesterWS">
        <operation name="add">
            <input wsam:Action="http://timedtester.org/TimedTesterWS/addRequest" message="tns:add"/>
            <output wsam:Action="http://timedtester.org/TimedTesterWS/addResponse" message="tns:addResponse"/>
        </operation>
        <operation name="addAsync">
            <input wsam:Action="http://timedtester.org/TimedTesterWS/addAsyncRequest" message="tns:addAsync"/>
            <output wsam:Action="http://timedtester.org/TimedTesterWS/addAsyncResponse" message="tns:addAsyncResponse"/>
        </operation>
    </portType>
    
    <binding name="TimedTesterWSPortBinding" type="tns:TimedTesterWS">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
        <operation name="add">
            <soap:operation soapAction=""/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
        
        <operation name="addAsync">
            <soap:operation soapAction=""/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
        
    </binding>
    
    <service name="TimedTesterWS">
        <port name="TimedTesterWSPort" binding="tns:TimedTesterWSPortBinding">
            <soap:address location="http://localhost/nowhere"/>
        </port>
    </service>
</definitions>